#ifndef ISAAC_ROS_IMAGE_PROC_DETECT_LASER_HPP_
#define ISAAC_ROS_IMAGE_PROC_DETECT_LASER_HPP_

#include <isaac_ros_image_proc/detect_laser_parameters.hpp> // generated by generate parameter library

#include "isaac_ros_managed_nitros/managed_nitros_subscriber.hpp"
#include "isaac_ros_nitros_image_type/nitros_image_view.hpp"
#include "isaac_ros_nitros_image_type/nitros_image.hpp"
#include "isaac_ros_managed_nitros/managed_nitros_publisher.hpp"

#include <cuda_runtime.h>

#include <opencv2/opencv.hpp>
#include <opencv2/core/cuda.hpp>
#include <opencv2/cudaimgproc.hpp>
#include <opencv2/cudafilters.hpp>
#include <opencv2/cudaarithm.hpp>

#include <pcl/point_cloud.h>
#include <pcl/point_types.h>

#include <Eigen/Dense>

namespace nvidia
{
    namespace isaac_ros
    {
        namespace image_proc
        {
            class DetectLaserNode : public rclcpp::Node
            {
            public:
                explicit DetectLaserNode(const rclcpp::NodeOptions options = rclcpp::NodeOptions());
                ~DetectLaserNode() final;

            private:
                void input_callback(const nvidia::isaac_ros::nitros::NitrosImageView &view);
                void pts_norm_to_3d(const std::vector<cv::Point2f> &pts_norm,
                                    pcl::PointCloud<pcl::PointXYZ>::Ptr pts_3d);

                // Qos???

                // Subscription to NitrosImage messages
                std::shared_ptr<nvidia::isaac_ros::nitros::ManagedNitrosSubscriber<
                    nvidia::isaac_ros::nitros::NitrosImageView>>
                    nitros_sub_ptr_;

                // Publisher for NitrosImage messages
                std::shared_ptr<nvidia::isaac_ros::nitros::ManagedNitrosPublisher<
                    nvidia::isaac_ros::nitros::NitrosImage>>
                    nitros_pub_ptr_;

                // Parameters and parameter listener
                std::shared_ptr<detect_laser_node::ParamListener> param_listener_;
                detect_laser_node::Params params_;

                // CUDA-related variables

                double frame_rate_display_;

                std::vector<cv::Point2f> laser_points_;
                cv::Rect laser_roi_;

                // Camera model and laser plane
                Eigen::Vector4d plane_;
                cv::Mat camera_matrix_;
                cv::Mat dist_coeffs_;

                cudaStream_t stream_;
            };
        } // namespace image_proc
    } // namespace isaac_ros
} // namespace nvidia

#endif // ISAAC_ROS_IMAGE_PROC_DETECT_LASER_HPP_