#ifndef ISAAC_ROS_IMAGE_PROC_MASKING_HPP_
#define ISAAC_ROS_IMAGE_PROC_MASKING_HPP_

#include <isaac_ros_image_proc/masking_parameters.hpp> // generated by generate parameter library

#include "isaac_ros_managed_nitros/managed_nitros_subscriber.hpp"
#include "isaac_ros_nitros_image_type/nitros_image_view.hpp"
#include "isaac_ros_nitros_image_type/nitros_image.hpp"
#include "isaac_ros_managed_nitros/managed_nitros_publisher.hpp"

#include <cuda_runtime.h>

#include <opencv2/opencv.hpp>
#include <opencv2/core/cuda.hpp>
#include <opencv2/cudaimgproc.hpp>
#include <opencv2/cudafilters.hpp>
#include <opencv2/cudaarithm.hpp>

namespace nvidia
{
    namespace isaac_ros
    {
        namespace image_proc
        {
            class MaskingNode : public rclcpp::Node
            {
            public:
                explicit MaskingNode(const rclcpp::NodeOptions options = rclcpp::NodeOptions());
                ~MaskingNode() final;

            private:
                void input_callback(const nvidia::isaac_ros::nitros::NitrosImageView &view);

                // Qos???

                // Subscription to NitrosImage messages
                std::shared_ptr<nvidia::isaac_ros::nitros::ManagedNitrosSubscriber<
                    nvidia::isaac_ros::nitros::NitrosImageView>>
                    nitros_sub_ptr_;

                // Publisher for NitrosImage messages
                std::shared_ptr<nvidia::isaac_ros::nitros::ManagedNitrosPublisher<
                    nvidia::isaac_ros::nitros::NitrosImage>>
                    nitros_pub_ptr_;

                // Parameters and parameter listener
                std::shared_ptr<masking_node::ParamListener> param_listener_;
                masking_node::Params params_;

                // CUDA-related variables
                cv::cuda::GpuMat input_hsv_;
                // cv::cuda::GpuMat hsv_mask_;
                cv::cuda::GpuMat mask1_;
                cv::cuda::GpuMat mask2_;

                // Morphology filters
                cv::Ptr<cv::cuda::Filter> dilate_filter;
                cv::Ptr<cv::cuda::Filter> close_filter;
                cv::Mat mask_dilate_kernel;
                cv::Mat mask_close_kernel;

                double frame_rate_display_;

                cudaStream_t stream_;
            };
        } // namespace image_proc
    } // namespace isaac_ros
} // namespace nvidia

#endif // ISAAC_ROS_IMAGE_PROC_MASKING_HPP_