#ifndef ISAAC_ROS_IMAGE_PROC_MORPHOLOGY_NODE_HPP_
#define ISAAC_ROS_IMAGE_PROC_MORPHOLOGY_NODE_HPP_

#include <isaac_ros_image_proc/morphology_parameters.hpp> // generated by generate parameter library

#include "isaac_ros_managed_nitros/managed_nitros_subscriber.hpp"
#include "isaac_ros_nitros_image_type/nitros_image_view.hpp"
#include "isaac_ros_nitros_image_type/nitros_image.hpp"
#include "isaac_ros_managed_nitros/managed_nitros_publisher.hpp"

#include <cuda_runtime.h>
#include <nvcv/Tensor.hpp>
#include <cvcuda/OpMorphology.hpp>

namespace nvidia
{
    namespace isaac_ros
    {
        namespace image_proc
        {

            class MorphologyNode : public rclcpp::Node
            {
            public:
                explicit MorphologyNode(const rclcpp::NodeOptions &options);
                ~MorphologyNode() final;

            private:
                void input_callback(const nvidia::isaac_ros::nitros::NitrosImageView &view);

                // Subscription to NitrosImage messages
                std::shared_ptr<nvidia::isaac_ros::nitros::ManagedNitrosSubscriber<
                    nvidia::isaac_ros::nitros::NitrosImageView>>
                    nitros_sub_ptr_;

                // Publisher for NitrosImage messages
                std::shared_ptr<nvidia::isaac_ros::nitros::ManagedNitrosPublisher<
                    nvidia::isaac_ros::nitros::NitrosImage>>
                    nitros_pub_ptr_;

                // Parameters and parameter listener
                std::shared_ptr<morphology_node::ParamListener> param_listener_;

                // Varaibles for parameters
                uint32_t batch_size_;
                int32_t kernel_width_;
                int32_t kernel_height_;
                NVCVMorphologyType morph_type_;
                NVCVBorderType border_type_;

                // NVCV Tensors and corresponding GPU buffer (strided)
                nvcv::TensorDataStridedCuda::Buffer input_image_buffer_;
                nvcv::Tensor input_image_tensor_;

                nvcv::TensorDataStridedCuda::Buffer output_image_buffer_;
                nvcv::Tensor output_image_tensor_;
                nvcv::Tensor workspace_tensor_;

                // Operator
                cvcuda::Morphology morphology_op_;

                // CUDA stream
                cudaStream_t stream_;
            };

        } // namespace image_proc
    } // namespace isaac_ros
} // namespace nvidia

#endif // ISAAC_ROS_IMAGE_PROC_MORPHOLOGY_NODE_HPP_