#ifndef ISAAC_ROS_IMAGE_PROC_OPENCV_MEDIAN_BLUR_HPP_
#define ISAAC_ROS_IMAGE_PROC_OPENCV_MEDIAN_BLUR_HPP_

#include <isaac_ros_image_proc/opencv_median_blur_parameters.hpp> // generated by generate parameter library

#include "isaac_ros_managed_nitros/managed_nitros_subscriber.hpp"
#include "isaac_ros_nitros_image_type/nitros_image_view.hpp"
#include "isaac_ros_nitros_image_type/nitros_image.hpp"
#include "isaac_ros_managed_nitros/managed_nitros_publisher.hpp"

#include <cuda_runtime.h>

#include <opencv2/opencv.hpp>
#include <opencv2/core/cuda.hpp>
#include <opencv2/cudaimgproc.hpp>
#include <opencv2/cudafilters.hpp>

namespace nvidia
{
    namespace isaac_ros
    {
        namespace image_proc
        {
            class OpencvMedianBlurNode : public rclcpp::Node
            {
            public:
                explicit OpencvMedianBlurNode(const rclcpp::NodeOptions options = rclcpp::NodeOptions());
                ~OpencvMedianBlurNode() final;

            private:
                void input_callback(const nvidia::isaac_ros::nitros::NitrosImageView &view);

                // Qos???

                // Subscription to NitrosImage messages
                std::shared_ptr<nvidia::isaac_ros::nitros::ManagedNitrosSubscriber<
                    nvidia::isaac_ros::nitros::NitrosImageView>>
                    nitros_sub_ptr_;

                // Publisher for NitrosImage messages
                std::shared_ptr<nvidia::isaac_ros::nitros::ManagedNitrosPublisher<
                    nvidia::isaac_ros::nitros::NitrosImage>>
                    nitros_pub_ptr_;

                // Parameters and parameter listener
                std::shared_ptr<opencv_median_blur_node::ParamListener> param_listener_;
                opencv_median_blur_node::Params params_;

                cv::Ptr<cv::cuda::Filter> median_filter_;
                double frame_rate_display_;

                cudaStream_t stream_;
            };
        } // namespace image_proc
    } // namespace isaac_ros
} // namespace nvidia

#endif // ISAAC_ROS_IMAGE_PROC_OPENCV_MEDIAN_BLUR_HPP_
