#ifndef ISAAC_ROS_IMAGE_PROC_RESIZE_HPP_
#define ISAAC_ROS_IMAGE_PROC_RESIZE_HPP_

#include <isaac_ros_image_proc/resize_parameters.hpp> // generated by generate parameter library

#include "isaac_ros_managed_nitros/managed_nitros_subscriber.hpp"
#include "isaac_ros_nitros_image_type/nitros_image_view.hpp"
#include "isaac_ros_nitros_image_type/nitros_image.hpp"
#include "isaac_ros_managed_nitros/managed_nitros_publisher.hpp"

#include <cuda_runtime.h>
#include <nvcv/Tensor.hpp>
#include <cvcuda/OpResize.hpp>

namespace nvidia
{
    namespace isaac_ros
    {
        namespace image_proc
        {

            class Resize : public rclcpp::Node
            {
            public:
                explicit Resize(const rclcpp::NodeOptions options = rclcpp::NodeOptions());
                ~Resize() final;

            private:
                void input_callback(const nvidia::isaac_ros::nitros::NitrosImageView &view);

                // Qos???

                // Subscription to NitrosImage messages
                std::shared_ptr<nvidia::isaac_ros::nitros::ManagedNitrosSubscriber<
                    nvidia::isaac_ros::nitros::NitrosImageView>>
                    nitros_sub_ptr_;

                // Publisher for NitrosImage messages
                std::shared_ptr<nvidia::isaac_ros::nitros::ManagedNitrosPublisher<
                    nvidia::isaac_ros::nitros::NitrosImage>>
                    nitros_pub_ptr_;

                // Parameters and parameter listener
                std::shared_ptr<resize_node::ParamListener> param_listener_;
                resize_node::Params params_;

                // Variables for parameters
                NVCVInterpolationType interpolation_type_;

                // Operator
                cvcuda::Resize resize_op_;
                // CUDA stream
                cudaStream_t stream_;
            };

        } // namespace image_proc
    } // namespace isaac_ros
} // namespace nvidia

#endif // ISAAC_ROS_IMAGE_PROC_RESIZE_HPP_
