#ifndef ISAAC_ROS_IMAGE_PROC_TEST_NODE_HPP_
#define ISAAC_ROS_IMAGE_PROC_TEST_NODE_HPP_

#include <memory>
#include <string>

#include "rclcpp/rclcpp.hpp"
#include "sensor_msgs/msg/image.hpp"
#include "sensor_msgs/image_encodings.hpp"
#include "test_node_parameters.hpp" // generated by generate parameter library

#include "isaac_ros_managed_nitros/managed_nitros_subscriber.hpp"
#include "isaac_ros_nitros_image_type/nitros_image_view.hpp"
#include "isaac_ros_nitros_image_type/nitros_image_builder.hpp"
#include "isaac_ros_nitros_image_type/nitros_image.hpp"
#include "isaac_ros_managed_nitros/managed_nitros_publisher.hpp"

#include <cuda_runtime.h>
#include <nvcv/Image.hpp>
#include <nvcv/Tensor.hpp>
#include <nvcv/Size.hpp>
#include <cvcuda/OpCustomCrop.hpp>
#include <cvcuda/OpMedianBlur.hpp>

namespace nvidia
{
    namespace isaac_ros
    {
        namespace image_proc
        {

            class TestNode : public rclcpp::Node
            {
            public:
                explicit TestNode(const rclcpp::NodeOptions &options);
                virtual ~TestNode();

            private:
                void InputCallback(const nvidia::isaac_ros::nitros::NitrosImageView &view);

                // Subscription to NitrosImage messages
                std::shared_ptr<nvidia::isaac_ros::nitros::ManagedNitrosSubscriber<
                    nvidia::isaac_ros::nitros::NitrosImageView>>
                    nitros_sub_ptr_;

                // Publisher for the cropped image
                std::shared_ptr<nvidia::isaac_ros::nitros::ManagedNitrosPublisher<
                    nvidia::isaac_ros::nitros::NitrosImage>>
                    crop_nitros_pub_ptr_;

                // Parameters and parameter listener
                // std::shared_ptr<ParamListener> param_listener_;
                // Params params_;

                // Image parameters
                int input_image_width_;
                int input_image_height_;
                int input_image_channels_;

                // Batch size, crop parameters, and kernel size for median blur
                uint32_t batch_size_;
                int cropX;
                int cropY;
                int cropWidth;
                int cropHeight;
                int32_t kernelWidth;
                int32_t kernelHeight; // Changed variable name for consistency

                // Tensors and corresponding GPU buffer (strided) for input, blurred, and cropped images
                nvcv::TensorDataStridedCuda::Buffer input_image_buffer_;
                nvcv::Tensor input_image_tensor_;

                nvcv::TensorDataStridedCuda::Buffer blur_image_buffer_;
                nvcv::Tensor blur_image_tensor_;

                nvcv::TensorDataStridedCuda::Buffer crop_image_buffer_;
                nvcv::Tensor crop_image_tensor_;

                // ROI structure for cropping
                NVCVRectI crpRect_;

                // Operators for Crop and MedianBlur
                cvcuda::CustomCrop cropOp_;
                static constexpr int maxVarShapeBatchSize = 1;
                cvcuda::MedianBlur medianBlurOp_;

                // CUDA stream
                cudaStream_t stream;
            };

        } // namespace image_proc
    } // namespace isaac_ros
} // namespace nvidia

#endif // ISAAC_ROS_IMAGE_PROC_TEST_NODE_HPP_
