cvt_color_node:
  batch_size_:
    type: int
    default_value: 1
    description: "The default batch size of images"
  image_sub_topic_:
    type: string
    default_value: "/image_raw"
    description: "The topic on which the image is subscribed."
  image_pub_topic_:
    type: string
    default_value: "/hsv_image"
    description: "The topic on which the image is subscribed."
